name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant gradlew permissions
      run: chmod +x gradlew

    - name: Run tests and generate reports
      run: ./gradlew test jacocoTestReport allureReport

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.1
      with:
        allure-results: build/allure-results

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          build/reports/**
          build/allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/allure-report
        keep_files: true

    - name: Spotless check
      run: ./gradlew spotlessCheck