name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant gradlew permissions
      run: chmod +x gradlew

    - name: Run tests and generate reports
      run: ./gradlew test jacocoTestReport allureReport

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # Исправлено на v4
      with:
        name: reports
        path: |
          build/reports/allure-report/allureReport
          build/jacoco/test/html

    - name: Deploy Allure Report to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4  # Обновлено до v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/reports/allure-report/allureReport

    - name: Spotless check
      run: ./gradlew spotlessCheck
    
    - name: Apply code formatting with Spotless
      run: ./gradlew spotlessApply